name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint & Test (placeholder)
        run: |
          python -c "import flask; print('flask ok', flask.__version__)"
      - name: Build image
        run: docker build -t ais-chatrooms-api:ci .